- src/main/java/com/curateme/claco/global/entity/ActiveStatus.java
- src/main/java/com/curateme/claco/global/entity/BaseEntity.java
- src/main/java/com/curateme/claco/member/entity/Member.java
- src/main/java/com/curateme/claco/member/entity/MemberType.java
#4 
- BaseEntity 생성
- Member 엔티티 생성
- BaseEntity 생성 (활성 상태, 생성일, 수정일 관리)
- ActiveStatus 생성 (활성, 비활성)
- Member 엔티티 생성
- MemberType 생성 (회원 가입 중, 회원 가입 완료, 관리자)
- 현재 기능 명세서 변경으로인한 테이블 설계 변경 예정으로 우선 2개만 먼저 PR 올립니다!
@anselmo228
> Feature: 엔티티 생성을 위한 기본 설정 및 Member 엔티티 생성

- src/main/java/com/curateme/claco/clacobook/domain/entity/ClacoBook.java
- src/main/java/com/curateme/claco/member/domain/entity/Member.java
Resolves #15 
- ClacoBook 엔티티 생성 및 매핑
- ClacoBook 엔티티 생성 (다대일 Member 매핑)
- Member 엔티티 매핑 (양방향)
@anselmo228
> ClacoBook 엔티티 생성

- src/main/java/com/curateme/claco/clacobook/controller/ClacoBookController.java
- src/main/java/com/curateme/claco/clacobook/domain/dto/request/UpdateClacoBookRequest.java
- src/main/java/com/curateme/claco/clacobook/domain/dto/response/ClacoBookResponse.java
- src/main/java/com/curateme/claco/clacobook/domain/entity/ClacoBook.java
- src/main/java/com/curateme/claco/clacobook/repository/ClacoBookRepository.java
- src/main/java/com/curateme/claco/clacobook/service/ClacoBookService.java
- src/main/java/com/curateme/claco/clacobook/service/ClacoBookServiceImpl.java
- src/main/java/com/curateme/claco/global/entity/BaseEntity.java
- src/main/java/com/curateme/claco/global/response/ApiStatus.java
- src/main/java/com/curateme/claco/member/domain/entity/Member.java
- src/main/java/com/curateme/claco/member/repository/MemberRepository.java
- src/main/java/com/curateme/claco/preference/domain/entity/Preference.java
- src/main/java/com/curateme/claco/preference/domain/entity/RegionPreference.java
- src/main/java/com/curateme/claco/preference/domain/entity/TypePreference.java
- src/test/java/com/curateme/claco/clacobook/repository/ClacoBookRepositoryTest.java
- src/test/java/com/curateme/claco/clacobook/service/ClacoBookServiceTest.java
- src/test/java/com/curateme/claco/member/repository/MemberRepositoryTest.java
Resolves #16 
Resolves #14 
- 클라코 북 CRUD 추가
- 클라코 북 도메인 메서드 관련 테스트 코드 추가
- 논리 삭제 조건 추가
- ClacoBook Repository, Service, Controller 추가
- ClacoBook Repository, Service 테스트 코드 추가 (TDD)
- 논리 삭제(Soft Delete) 조건 추가
- 논리 삭제의 경우 조건을 추가해두어 특별한 상황이 아니면 고려하실 일 없을 겁니다! 추후 엔티티 생성 시에도 기존 코드 참고하여 조건 추가해주시면 감사하겠습니다!
@anselmo228
> Feature: 클라코 북 CRUD 및 논리 삭제 조건 추가

- build.gradle
- src/main/java/com/curateme/claco/clacobook/controller/ClacoBookController.java
- src/main/java/com/curateme/claco/global/config/SwaggerConfig.java
- Swagger Gradle 추가
- Swagger Template 작성
- Swagger Controller 예제
- http://localhost:8080/swagger-ui/index.html#/ 에 접속시
- Claco Book Controller에 Swagger 예제
summary - 기능 설명, description - 기능명세서 화면번호 명세
- JWT 토큰은 각 contoller 우측 상단의 자물쇠로 입력 가능합니다.
> Feature: swagger config

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- src/main/java/com/curateme/claco/global/config/SecurityConfig.java
- src/main/java/com/curateme/claco/review/domain/entity/TicketReview.java
- src/main/java/com/curateme/claco/review/repository/PlaceCategoryRepository.java
- src/main/java/com/curateme/claco/review/repository/PlaceReviewRepository.java
- src/main/java/com/curateme/claco/review/repository/ReviewImageRepository.java
- src/main/java/com/curateme/claco/review/repository/TicketReviewRepository.java
- Swagger filter pass 추가 및 TicketReview 수정
- Review 관련 도메인 Repository 추가
- Swagger 관련 uri JWT 필터 통과하도록 수정
- TicketReview 요구사항 변경에 따른 ticketPrice 필드 삭제
- Review 관련 도메인 Repository 추가
- 우선 필요하실 것 같아서 빠르게 PR 보내놓습니다!
@anselmo228
> Requirement: Review 관련 도메인 Repository 추가, filter pass 추가 및 TicketReview 수정

- build.gradle
- src/main/java/com/curateme/claco/global/config/S3Config.java
- src/main/java/com/curateme/claco/global/response/ApiStatus.java
- src/main/java/com/curateme/claco/global/util/S3Util.java
- src/main/resources/application-aws.yml
- src/main/resources/application.yml
resolves #33 
- MultiPartFile 전송을 위한 S3 연결
- AWS S3 SDK 추가
- S3Util 추가 (파일 업로드 유틸)
- 환경변수 사용에 유의해주세요.
- 사전에 제공해드린 키와 버킷 이름을 사용하시기 바랍니다.
@anselmo228
> Feature: S3 연결

- src/main/java/com/curateme/claco/concert/domain/entity/Concert.java
- src/main/java/com/curateme/claco/member/domain/entity/Member.java
- src/main/java/com/curateme/claco/review/controller/PlaceCategoryController.java
- src/main/java/com/curateme/claco/review/controller/TagCategoryController.java
- src/main/java/com/curateme/claco/review/domain/entity/PlaceCategory.java
- src/main/java/com/curateme/claco/review/domain/entity/PlaceReview.java
- src/main/java/com/curateme/claco/review/domain/entity/ReviewImage.java
- src/main/java/com/curateme/claco/review/domain/entity/ReviewTag.java
- src/main/java/com/curateme/claco/review/domain/entity/TagCategory.java
- src/main/java/com/curateme/claco/review/domain/entity/TicketReview.java
- src/main/java/com/curateme/claco/review/domain/vo/ImageUrlVO.java
- src/main/java/com/curateme/claco/review/domain/vo/PlaceCategoryVO.java
- src/main/java/com/curateme/claco/review/domain/vo/TagCategoryVO.java
- src/main/java/com/curateme/claco/review/repository/ReviewTagRepository.java
- src/main/java/com/curateme/claco/review/repository/TagCategoryRepository.java
- src/main/java/com/curateme/claco/review/service/PlaceCategoryService.java
- src/main/java/com/curateme/claco/review/service/PlaceCategoryServiceImpl.java
- src/main/java/com/curateme/claco/review/service/TagCategoryService.java
- src/main/java/com/curateme/claco/review/service/TagCategoryServiceImpl.java
- src/test/java/com/curateme/claco/review/service/PlaceCategoryServiceTest.java
- src/test/java/com/curateme/claco/review/service/TagCategoryServiceTest.java
- VO 추가
- 장소평 및 감상 태그 리스트 기능
- 쿼리 최적화를 위한 Member - Preference Fetch 타입 Lazy 변경
- soft delete 쿼리 오류 변경
- VO 추가
- 장소평 및 감상 태그 리스트 기능 -> test 코드도 추가
- 쿼리 최적화를 위한 Member - Preference Fetch 타입 Lazy 변경
- soft delete 쿼리 오류 변경 -> 오타 수정
- 후에 구현 사항이 많아 나눠서 PR 날립니다!
@anselmo228
> Feature: 장소평 및 감상 태그 리스트 추가 및 자잘한 추가/변경

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
- src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertService.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- src/main/java/com/curateme/claco/global/response/PageResponse.java
- 공연 정보를 불러오는는 API 입니다.
- PathVariable: 카테고리명, 정렬 기준
- RequestParam: page, size 페이지네이션
- 또한 페이지네이션에서 총 컨텐츠 갯수를 반환합니다.
-
> [Feature] 화면번호 4.0.0 둘러보기

- src/main/java/com/curateme/claco/member/domain/entity/Member.java
- src/main/java/com/curateme/claco/member/repository/MemberRepository.java
- src/main/java/com/curateme/claco/preference/controller/PreferenceController.java
- src/main/java/com/curateme/claco/preference/domain/dto/request/PreferenceUpdateRequest.java
- src/main/java/com/curateme/claco/preference/domain/dto/response/PreferenceInfoResponse.java
- src/main/java/com/curateme/claco/preference/domain/entity/Preference.java
- src/main/java/com/curateme/claco/preference/domain/vo/RegionPreferenceVO.java
- src/main/java/com/curateme/claco/preference/domain/vo/TypePreferenceVO.java
- src/main/java/com/curateme/claco/preference/service/PreferenceService.java
- src/main/java/com/curateme/claco/preference/service/PreferenceServiceImpl.java
- src/test/java/com/curateme/claco/member/repository/MemberRepositoryTest.java
- src/test/java/com/curateme/claco/preference/service/PreferenceServiceTest.java
resolves #39 
resolves #40 
- 취향 조회 및 수정 기능 추가
- PreferenceService 조회, 수정 기능 추가 / 테스트 코드 추가
- MemberRepository preference 조인 기능 추가 / 테스트 코드 추가
- Swagger API 애노테이션 추가
- 스웨거 API docs도 남겨봤습니다! 확인 부탁드립니다!
@anselmo228
> Feature: 취향 조회 및 수정 기능 추가

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
- src/main/java/com/curateme/claco/concert/domain/entity/Concert.java
- src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertService.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- https://github.com/Curate-Me/claco-server/issues/44
- 필터맇해서 공연 정보 조회
- 검색어입력으로 공연 정보 조회 
- 필터링에서 가격 필터링은 현재 제외한 상태입니다. 
- 콘서트 조회 관련 API 는 끝입니다.
> [Feature] Concert CRUD

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/domain/dto/request/ConcertLikesRequest.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertCategoryResponse.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
- src/main/java/com/curateme/claco/concert/domain/entity/Category.java
- src/main/java/com/curateme/claco/concert/domain/entity/ConcertCategory.java
- src/main/java/com/curateme/claco/concert/domain/entity/ConcertLike.java
- src/main/java/com/curateme/claco/concert/repository/CategoryRepository.java
- src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
- src/main/java/com/curateme/claco/concert/repository/ConcertLikeRepository.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertService.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- 공연 상세보기
- 좋아요 등록/취소하기
- 공연 상세보기 
-> 기존 공연 정보 + 카테고리 리스트(카테고리명, 이미지 S3 URL)
- 좋아요 등록 및 취소
-> 좋아요가 등록되어 있다면 좋아요 취소로, 좋아요가 등록되지 않았따면 좋아요 생성으로 
-
> [Feature] Concert 상세보기 및 좋아요 등록하기

- src/main/java/com/curateme/claco/preference/service/PreferenceServiceImpl.java
- 사용자 취향 입력시 FLASK 서버로 전송 후 CSV파일 업데이트
Pipeline
1. 사용자가 취향 입력
2. 취향 메인 DB 저장
3. 취향 리스트 FLASK로 전송
4. FLASK에서 받아서 CSV파일 업로드 -> 추천시스템이 학습할 수 있는 방식으로
5. 
-
> [Feature] #55 feature 사용자 취향

- build.gradle
- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/repository/ConcertLikeRepository.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
- src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertsResponse.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- 추천시스템 로직 구현
1. 유저 취향 기반 추천
- 유저의 취향과 비슷한 공연 5개를 추천해줍니다.
2. 유저가 최근 좋아요한 공연 기반 추천(키워드)
- Flask API URL은 추후 환경변수로 변경하도록 하겠습니다..ㅎㅎ
> [Feature]#57 feature 추천시스템 로직

- .github/workflows/ci-cd.yml
- src/main/java/com/curateme/claco/preference/service/PreferenceServiceImpl.java
- src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- src/main/resources/application-aws.yml
- 유저 아이디를 securitycontextutil의 Member Entity에서 추출하도록 변경
- Flask 서버를 os 환경에서 접근할수 있도록 변경
- https://github.com/Curate-Me/claco-server/issues/61
-
> [Fix] fix securitycontextutil & Flask URL

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertLikedResponse.java
- src/main/java/com/curateme/claco/concert/repository/ConcertLikeRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertService.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- 내가 좋아요한 공연 조회하기 
- Request: Query(검색어),  Genre
- Response: 공연 리스트
-
> [Feature] #63 feature 마이페이지

- src/main/java/com/curateme/claco/concert/repository/ConcertLikeRepository.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- https://github.com/Curate-Me/claco-server/issues/65
- 
-
> [Refactoring]#65 refactoring 공연추천 예외처리

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/domain/dto/request/ConcertLikesRequest.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertCategoryResponse.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertClacoBookResponse.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertLikedResponse.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
- src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
- src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertsResponseV1.java
> [refactoring] DTO Schema Description

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewInfoResponse.java
resolves #72 
- 티켓 리뷰 상세 조회 데이터 추가
- 쿠키 버그 픽스
- 티켓 리뷰 상세 조회 데이터에서 티켓 이미지 추가
- JwtAuthenticationFilter에서 쿠키 발급 시 정책 부분 오타 수정
- 객체 지향 설계 덕분에 변경이 적습니다 👍
@anselmo228
> Requirements: 티켓리뷰 상세 조회 데이터 추가 및 쿠키 버그 픽스

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- 리프레시 토큰 임시 제외
- 프론트엔드 테스트를 위한 리프레시 토큰 임시 제외
@anselmo228
> hotfix: 리프레시 토큰 임시 제외

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertAutoCompleteResponse.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertService.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
- src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertResponseV3.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- 추가 요구사항 및 수정 사항 반영
1. 좋아요 기반 추천에서 좋아요 기록이 있는지 없는지 Boolean 타입으로 필드 추가
2. 둗러보기 날짜 필터링 수정
3. 자동완성 API 추가
4. 공연 검색시 종료 공연 필터링
- 작업하면서 추가 요구사항이 많이 생겨서 동시에 PR 올리는 점 양해부탁드립니다
> Refactoring/#69 자동완성 및 수정기능

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertService.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- 추가 기능 수정 및 리팩토링
1. Concert Detail & Concert Response 불필요한 필드 제거
2. Concert 필터링에서 카테고리 필터 추가
3. 쿼리문 수정
-
> [FIX] Concert Domain

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
- src/main/java/com/curateme/claco/concert/domain/entity/Concert.java
- Concert Table에서 공연 요약 (Concert Summary) 필드를 추가하였습니다
- Concert Entity 및 Response에 summary 필드 추가
- 요약되는 Flow는 AI Server 와 Batch 서버 최근 PR 확인해보시면 됩니다!
> [Requirements] 공연 요약 필드 추가

- src/main/java/com/curateme/claco/authentication/handler/oauth/OAuthLoginSuccessHandler.java
resolves #85 
resolves #86 
- 닉네임으로 인한 로그인 오류 수정
- 로그인 시 닉네임 조회 로직 MEMBER 일 시에만 추가하도록 수정
@anselmo228
> hotfix: 로그인 오류 수정 (닉네임)

- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewSimpleResponse.java
- src/main/java/com/curateme/claco/review/repository/TicketReviewRepository.java
- Concert Detail Response 수정 
- Test code 제거
-
> feature: ConcertDetail Response 수정

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- src/main/java/com/curateme/claco/authentication/util/RefreshContextHolder.java
- src/main/java/com/curateme/claco/clacobook/controller/ClacoBookController.java
- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/global/annotation/RefreshedAspect.java
- src/main/java/com/curateme/claco/global/annotation/TokenRefreshedCheck.java
- src/main/java/com/curateme/claco/global/response/ApiResponse.java
- src/main/java/com/curateme/claco/member/controller/MemberController.java
- src/main/java/com/curateme/claco/preference/controller/PreferenceController.java
- src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
- src/main/java/com/curateme/claco/review/controller/PlaceCategoryController.java
- src/main/java/com/curateme/claco/review/controller/TagCategoryController.java
- src/main/java/com/curateme/claco/review/controller/TicketReviewController.java
resolves #94 
- 토큰이 재발급되었는지 확인하는 AOP 적용
- RefreshedToken Thread Local 생성 및 적용
- 토큰 재발급 확인용 annotation, AOP 생성 및 적용
@anselmo228
> Feature: 토큰 재발급 확인 AOP

- .github/workflows/ci-cd.yml
- Dockerfile
- docker-compose.yml
- dockerfiles/dockerfile-nginx
- dockerfiles/dockerfile-server
- dockerfiles/nginx.conf
- src/main/java/com/curateme/claco/global/controller/HealthCheckController.java
resolves #92 
- Docker 사용 환경에서 docker compose 사용 환경으로 마이그레이션
- Nginx 및 nginx.conf 추가
- docker-compose 사용 환경으로 마이그레이션
- CI/CD 스크립트 수정
- 헬스 체크용 Probe -> HealthCheck로 명칭 변경
- PR 확인 후 머지는 추후에 하겠습니다! 머지는 바로 하지 말아주세요!
@anselmo228
> Chore: Docker 환경 마이그레이션

- .github/workflows/ci-cd.yml
- CI/CD 스크립트 Docker 세팅 추가
- CI/CD 스크립트 Docker 세팅 추가
@anselmo228
> hotfix: Docker setup 추가

- .github/workflows/ci-cd.yml
- docker-compose 가 안되는 문제 해결 중
- docker 최신 버전에 따라 docker compose 로 변경
> hotfix: fix ci-cd docker-compose

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- src/main/java/com/curateme/claco/global/config/SecurityConfig.java
- 헬스 체크 URI 권한 개방
-  헬스 체크 URI 권한 개방
- JWT 필터 패스
- Authority 패스
> hotfix: 헬스 체크 URI 개방

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/repository/ConcertCategoryRepository.java
- src/main/java/com/curateme/claco/concert/repository/ConcertLikeRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertService.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
- src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertResponseV3.java
- src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertsResponseV1.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- src/test/java/com/curateme/claco/concert/repository/ConcertLikeRepositoryTest.java
- src/test/java/com/curateme/claco/concert/service/ConcertServiceTest.java
-Concert & Recommendations Service 수정
1. ConcertResponse 수정
2. Liked Recommendation Query 수정
3. 선택한 공연과 비슷한 공연 추천 API 추가
4. Builder 수정
- 테스트 코드 오늘안으로 얼른 마무리 하겠스빈다..ㅠ
> [Fix & Requirements] Concert & Recommendations Service 수정

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertResponseV3.java
- src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertsResponseV1.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
> [hotfix] 추천 Response 수정 및 URL 수정

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/recommendation/controller/RecommendationController.java
- src/main/java/com/curateme/claco/recommendation/domain/dto/RecommendationConcertResponseV2.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationService.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewSummaryResponse.java
- src/main/java/com/curateme/claco/review/repository/TicketReviewRepository.java
- 요구사항 반영
1. 콘서트 조회시 all 필드 추가
2. direction 필드 default값 지정
3. 클라코북 추천 개수 및 반환값 수정
-
> [Requirements] Concert & Recommendations

- .github/workflows/ci-cd.yml
- build.gradle
- docker-compose.yml
- dockerfiles/nginx.conf
- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- src/main/java/com/curateme/claco/global/config/SecurityConfig.java
- src/main/resources/application.yml
- Prometheus와 Grafana를 활용한 모니터링 시스템 구축
- Prometheus Docker 이미지 추가
- Grafana Docker 이미지 추가
- Actuator 추가
- 서버에 Prometheus 관련 파일들 정의해두었습니다!
@anselmo228
> Chore: 모니터링 시스템 구축

- .github/workflows/ci-cd.yml
- docker-compose.yml
- CI/CD 과정에서 모니터링 프로세스 수정
- 이미지 태그 수정
- PR 시 CI/CD 돌아가도록 임시 수정
@anselmo228
> hotfix: 모니터링 CI/CD 프로세스 수정

- .github/workflows/ci-cd.yml
- PR 시 Deploy 복구
- 인프라 구성을 위해 열어놨던 PR 시 Deploy 되는 태스크를 복구
@anselmo228
> hotfix: PR 시 Deploy 복구

- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- 추천 공연 갯수를 온보딩 구성에 맞게 선택할수 있도록 합니다
-
-
> [requirements] 추천 공연 갯수 Custom

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- src/test/java/com/curateme/claco/concert/repository/ConcertCategoryRepositoryTest.java
- src/test/java/com/curateme/claco/concert/repository/ConcertLikeRepositoryTest.java
- src/test/java/com/curateme/claco/concert/repository/ConcertRepositoryTest.java
- src/test/java/com/curateme/claco/concert/service/ConcertServiceTest.java
- Concert Domain TestCode 완료
- Service Layer 빠진 메서드
- Repository 추가
-
> [TestCode] Concert TestCode 최종

- src/main/resources/application-prod.yml
- SQL문 옵션 제외
- SQL문 옵션 제외
@anselmo228
> chore: SQL문 옵션 제외

- src/main/java/com/curateme/claco/review/controller/TicketReviewController.java
- src/main/java/com/curateme/claco/review/service/TicketReviewServiceImpl.java
- 이미지 required 수정
- required false로 수정
- null 시 빈 객체 생성
@anselmo228
> fix: 이미지 required 및 처리 수정

- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponse.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- 공연 검색시 검색으로 아무것도 뜨지 않을경우 자동으로 공연 추천(3개)
- 서비스 레이어에서 조건문으로 수정
-
> [Requirements]: Concert 검색어 없을시 자동 추천

- src/main/java/com/curateme/claco/review/controller/TicketReviewController.java
- 이미지 null 오류 수정
- Controller 삼항 연산자 null 오타 수정
@anselmo228
> hotfix: 이미지 null 값 주는 오류 수정

- src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewInfoResponse.java
- src/main/java/com/curateme/claco/review/service/TicketReviewServiceImpl.java
- 리뷰 생성 시 클라코북 id 반환
- TicketReviewInfoResponse clacobookId 필드 및 업데이트 메서드 추가
- create 요청에 클라코북 id 업데이트 추가
@anselmo228
> requirements: 리뷰 생성 시 클라코북 id 반환

- src/main/java/com/curateme/claco/member/service/MemberServiceV1.java
- 이미지 empty 체크 삭제
- 이미지 empty 체크 삭제
@anselmo228
> hotfix: 이미지 empty 체크 삭제

- src/test/java/com/curateme/claco/review/service/TicketReviewServiceTest.java
- 티켓 이동 테스트 추가
- 클라코북 간 티켓 이동 테스트 추가
@anselmo228
> Test: 티켓 이동 테스트 추가

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponseV2.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertService.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- src/main/java/com/curateme/claco/global/response/PageResponse.java
- src/test/java/com/curateme/claco/concert/repository/ConcertRepositoryTest.java
- src/test/java/com/curateme/claco/concert/service/ConcertServiceTest.java
- src/test/java/com/curateme/claco/recommendation/RecommendationServiceTest.java
- 좋아요한 공연 쿼리 default 추가
- 좋아요한 공연 DTO 변경
- Pagination 변경
-
> [Hotfix] Concert Service 수정

- dockerfiles/nginx.conf
- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponseV2.java
- nginx connection 증가
- nginx connection worker 1024 -> 4096 으로 증가
@anselmo228
> chore: nginx worker connection 증가

- src/main/java/com/curateme/claco/review/domain/dto/response/TicketReviewInfoResponse.java
- 티켓 리뷰 상세 조회시 콘서트 정보 반환
- 티켓 리뷰 상세 조회시 콘서트 장르, 콘서트 상태 추가
@anselmo228
> requirements: 티켓 리뷰 상세 조회시 콘서트 정보 반환

- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponseV2.java
- Concert Response DTO 네이밍 변경 및 추가
- isLiked 필드 추가 -> 서비스 레이어 변경
- status to prfstate
- add fcltynm
- isLiked Logic
-
> [Hotfix]: DTO Naming 변경및 추가

- src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertResponseV2.java
- DTO 필드 추가
- 좋아요 공연 둘러보기에서 liked 필드 추가
-
> [hotfix] liked 필드 추가

- src/main/java/com/curateme/claco/clacobook/repository/ClacoBookRepository.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- 한사람 당 여러개 클라코북 생성 가능하도록 변경
- Repository Query 및 클라코북 추천 로직 수정
-
> [hotfix]: Clacobook 여러개 추가 가능

- src/main/java/com/curateme/claco/clacobook/repository/ClacoBookRepository.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- TIcket Review Query 수정
- JPQL 방식: setMaxResults 사용
-
> [hotfix] TicketReview 여러개 추가 가능

- .github/workflows/ci-cd.yml
- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- src/main/java/com/curateme/claco/authentication/handler/oauth/OAuthLoginSuccessHandler.java
- src/main/java/com/curateme/claco/global/config/SecurityConfig.java
- src/main/java/com/curateme/claco/global/filter/ExceptionHandlerFilter.java
- src/main/resources/application-prod.yml
- src/test/resources/application-test.yml
- Exception 필터 추가 및 refresh token 검사 재배치
- Exception handler filter 추가 및 등록
- refresh token 검사 부활
@anselmo228
> Feature: Exception 필터 추가 및 refresh token 검사 재배치

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- 토큰 세팅 수정
- JWT 필터에서 토큰 세팅 수정
@anselmo228
> hotfix: Token 세팅 수정

- src/main/java/com/curateme/claco/concert/controller/ConcertController.java
- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- src/main/java/com/curateme/claco/concert/service/ConcertService.java
- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- src/test/java/com/curateme/claco/concert/service/ConcertServiceTest.java
- https://github.com/Curate-Me/claco-server/issues/148
1. Concert 세부사항 둘러보기 필터 area 배열로 수정
2. Review Tickets Limits to 3
-
> [hotfix]: Concert 필터 수정

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- refresh token 검사 부활
- refresh token 검사 부활
@anselmo228
> Refactor: refresh token 검사 부활

- src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
- src/main/java/com/curateme/claco/preference/service/PreferenceServiceImpl.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- soutv 제거
- Null Exception 방지
- ClacoBook에 리뷰가 없을 경우 다음 클라코북 탐색 진헹
- Sys 최대한 제거
-
> hotfix: remove soutv and null exception

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- 쿠키 체크 부활
- 쿠키 체크 부활 (배포용 세팅)
@anselmo228
> Refactor: 쿠키 부활

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- 리프레시 검사 취소
- 리프레시 검사 취소
@anselmo228
> refactor: refactor refresh

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- 리프레시 토큰 부활
- 리프레시 토큰 부활
@anselmo228
> refactor: 리프레시 토큰 부활

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- 환경 변수에 따른 쿠키 체크
- 환경 변수에 따른 쿠키 체크
@anselmo228
> feat: 환경 변수에 따른 쿠키 체크

- dockerfiles/nginx.conf
- src/main/resources/application.yml
resolves (#159 )
- 최대 파일 사이즈 설정
- Nginx 파일 사이즈 조정
- spring 파일 사이즈 조정 10MB -> 15MB
@anselmo228
> hotfix: 파일 사이즈 설정

- src/main/java/com/curateme/claco/concert/repository/ConcertRepository.java
- 리뷰 공연 둘러보기 전체 보여주기
- Query문 날짜 쿼리 제거
-
> [hotfix] 리뷰 공연 둘러보기 전체 보여주기

- src/main/java/com/curateme/claco/authentication/controller/AuthenticationController.java
- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- src/main/java/com/curateme/claco/authentication/handler/oauth/OAuthLoginSuccessHandler.java
- src/main/java/com/curateme/claco/authentication/service/AuthenticationService.java
- 모바일 정책으로 인한 리다이렉션 응답 쿠키 설정 제거
- 쿠키 받아오는 메서드 추가
@anselmo228
> Feature: 리프레시 쿠키 발급 메서드 추가

- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- refresh URI 체크 수정
- refresh URI 체크 수정
@anselmo228
> hotfix: refresh URI 체크 수정

- src/main/java/com/curateme/claco/clacobook/repository/ClacoBookRepository.java
- src/main/java/com/curateme/claco/recommendation/service/RecommendationServiceImpl.java
- 추천 Clacobook에 Ticket이나 Clacobook 자체가 없을 경우 예외처리
- 랜덤으로 Clacobook 3개 추천
-
> hotfix: Clacobook 없을경우 예외 처리

- .github/workflows/ci-cd.yml
- src/main/java/com/curateme/claco/authentication/filter/JwtAuthenticationFilter.java
- src/main/java/com/curateme/claco/authentication/service/AuthenticationService.java
- src/main/resources/application-prod.yml
- src/test/resources/application-test.yml
- 쿠키 도메인 추가
- 쿠키 도메인 추가
@anselmo228
> hotfix: 쿠키 도메인 추가
